config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users  do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }

  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at

  def finished_at_is_invalid_without_a_started_at
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
end

app/models/task.rb
class Task < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  
  belongs_to :user
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { in: 5..300 }
end

app/models/user.rb
class User < ApplicationRecord
   has_many :tasks, dependent: :destroy
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください。"
      redirect_to login_url
    end
  end
  
  # 現ログインユーザーであるか
  def correct_user
    redirect_to root_url unless current_user?(@user)
  end

  # 現ログインユーザーが管理者であるか
  def admin_user
    redirect_to root_url unless current_user.admin?
  end
  
  # @userが定義されている上で使用する
  def admin_or_correct
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = "権限がありません。"
      redirect_to root_url
    end  
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    if logged_in?
      flash[:info] = 'すでにログインしています。'
      redirect_to current_user
    end
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      flash[:success] = 'ログインしました。'
      redirect_to user
    else
      flash.now[:danger] = '認証に失敗しました。'
      render :new
    end
  end
  
  def destroy
    log_out if logged_in?
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_user
  before_action :set_task, only: %i(show edit update destroy)
  before_action :logged_in_user
  before_action :correct_user
  
  def index
    @tasks = @user.tasks
  end

  def show
  end

  def new
    @task = Task.new
  end
  
  def create
    @task = @user.tasks.build(task_params)
    if @task.save
      flash[:success] = "タスクを新規作成しました。"
      redirect_to user_tasks_url @user
    else
      render :new
    end
  end

  def edit
    
  end
  
  def update
    if @task.update_attributes(task_params)
      flash[:success] = "タスクを更新しました。"
      redirect_to user_task_url(@user, @task)
    else
      render :edit
    end
  end
  
  def destroy
    @task.destroy
    flash[:success] = "タスクを削除しました。"
    redirect_to user_tasks_url @user
  end
  
  private

    def task_params
      params.require(:task).permit(:name, :description)
    end
    
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_task
      unless @task = @user.tasks.find_by(id: params[:id])
        flash[:danger] = "権限がありません。"
        redirect_to user_tasks_url @user
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)
  before_action :logged_in_user, only: %i(index show edit update destroy)
  before_action :admin_user, only: %i(index destroy)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_or_correct, only: %i(show)
  
  def index
    @users = User.paginate(page: params[:page], per_page: 20)
  end
  
  def show
  end

  def new
    if logged_in? && !current_user.admin?
      flash[:info] = 'すでにログインしています。'
      redirect_to current_user
    end
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'ユーザーの新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_name = "")
    base_title = "Sample"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def current_user?(user)
    user == current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-default" id="header">
  <div class="container">
    <%= link_to "Task App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップ", root_path, class: "header-list" %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "利用者一覧", users_path, class: "header-list" %></li>
          <% end %>
          <li><%= link_to "タスク作成", new_user_task_path(current_user), class: "header-list" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle header-list" data-toggle="dropdown" id="dropdown-title">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="dropdown-header">ユーザー</li>
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="dropdown-header">タスク</li>
              <li><%= link_to "タスク一覧", user_tasks_path(current_user) %></li>
              
              <li class="divider"></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path, class: "header-list" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      入力した内容に<%= obj.errors.count %>件のエラーがあります。
    </div>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/top.html.erb
 <% provide(:title, "Top") %>

<div class="row">
  
  <div class="col-md-7">
    <div class="center jumbotron" id="top-main">
      <h1 id="top-main-title">TaskApp</h1>
      <p>TaskAppは簡易ToDo管理ツールです。</p>
      <p>↓↓初めてのご利用↓↓</p>
      <% if logged_in? %>
        <%= link_to "アカウント作成", signup_path, class: "btn btn-lg btn-success #{"disabled" unless current_user.admin?}" %>
      <% else %>
        <%= link_to "アカウント作成", signup_path, class: "btn btn-lg btn-success" %>
      <% end %>
    </div>
  </div>

  <div class="col-md-4">
    <h1>ログイン</h1>
    <%= form_with(scope: :session, url: login_path, local: true) do |f| %>
      <% if logged_in? %>
        <%= f.label :email, t("sessions.new.email"), class: "label-form" %>
        <%= f.email_field :email, class: 'form-control', readonly: true %>
  
        <%= f.label :password, t("sessions.new.password"), class: "label-form" %>
        <%= f.password_field :password, class: 'form-control', readonly: true %>
        
        <%= f.submit "ログイン状態です", class: "btn btn-primary btn-block btn-form", disabled: "disabled" %>
      <% else %>
        <%= f.label :email, t("sessions.new.email"), class: "label-form" %>
        <%= f.email_field :email, class: 'form-control' %>
  
        <%= f.label :password, t("sessions.new.password"), class: "label-form" %>
        <%= f.password_field :password, class: 'form-control' %>
        
        <%= f.label :remember_me, class: "checkbox inline checkbox-login", for: "remember-me" do %>
          <%= f.check_box :remember_me, id: "remember-me" %>
          <span>ログイン情報を記憶する</span>
        <% end %>
        
        <%= f.submit "ログイン", class: "btn btn-primary btn-block btn-form" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<% provide(:title, 'Edit Task') %>

<h1>タスク編集</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_with(model: @task, url: user_task_path(@user, @task), local: true, method: :patch) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { obj: @task } %>
      
      <%= f.label :name, class: "label-form" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, class: "label-form" %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>

      <%= f.submit "更新", class: "btn btn-primary btn-form" %>
      <%= link_to "キャンセル", user_tasks_path(@user), class: "btn btn-default btn-form" %>
    <% end %>
  </div>
</div>

app/views/tasks/index.html.erb
<% provide(:title, @user.name) %>

<h1><%= @user.name %>のタスク一覧</h1>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= link_to "タスク新規作成", new_user_task_path(@user), class: "btn btn-lg btn-primary pull-right" %>
    <table class="table table-hover" id="table-tasks">
      <thead>
        <tr>
          <th><%= Task.human_attribute_name :name %></th>
          <th><%= Task.human_attribute_name :created_at %></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @tasks.each do |task| %>
          <tr>
            <td><%= link_to task.name, user_task_path(@user, task), id: "task-name" %></td>
            <td><%= l(task.created_at, format: :long) %></td>
            <td>
              <%= link_to "編集", edit_user_task_path(@user, task), class: "btn btn-success" %>
              <%= link_to "削除", user_task_path(@user, task), method: :delete,
              data: { confirm: "「#{task.name}」を削除します。よろしいですか？" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>    
</div>

app/views/tasks/new.html.erb
<% provide(:title, 'New Task') %>

<h1>タスク新規作成</h1>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_with(model: @task, url: user_tasks_path(@user), local: true) do |f| %>
      <%= render partial: 'shared/error_messages', locals: { obj: @task } %>
      
      <%= f.label :name, class: "label-form" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :description, class: "label-form" %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>

      <%= f.submit "新規登録", class: "btn btn-lg btn-primary btn-form" %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<% provide(:title, @user.name) %>

<h1>タスク詳細</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-bordered" id="table-task">
      <tbody>
        <tr>
          <th class="active col-md-2"><%= Task.human_attribute_name :id %></th>
          <td class="col-md-10"><%= @task.id %></td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :name %></th>
          <td><%= @task.name %></td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :description %></th>
          <td>
            <%= auto_link(safe_join(@task.description.split("\n"), tag(:br))) %>
          </td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :created_at %></th>
          <td><%= l(@task.created_at, format: :long) %></td>
        </tr>
        <tr>
          <th class="active"><%= Task.human_attribute_name :updated_at %></th>
          <td><%= l(@task.updated_at, format: :long) %></td>
        </tr>
      </tbody>
    </table>
    
    <div>
      <%= link_to "編集", edit_user_task_path(@user, @task), class: "btn btn-lg btn-success" %>
      <%= link_to "削除", user_task_path(@user, @task), method: :delete,
      data: { confirm: "「#{@task.name}」を削除します。よろしいですか？" }, class: "btn btn-lg btn-danger" %>
    </div>
  </div>    
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render partial: 'shared/error_messages', locals: { obj: @user } %>

  <%= f.label :name, class: "label-form" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-form" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, class: "label-form" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-form" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:btn_text), class: "btn btn-primary btn-block btn-form" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, @user.name) %>
<% provide(:btn_text, '更新') %>

<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<h1>利用者一覧</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <%= will_paginate %>
    <table class="table table-condensed table-hover" id="table-users">
      <thead>
        <tr>
          <th><%= User.human_attribute_name :name %></th>
        </tr>
      </thead>
  
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to user.name, user %>
              <% if user.admin? %>
                <span class="label label-primary label-user-division">管理者</span>
              <% else %>
                <span class="label label-success label-user-division">一般</span>
              <% end %>
            </td>
            <td>
              <% unless user.admin? %>
                <%= link_to "削除", user, method: :delete,
                data: { confirm: "#{user.name}を削除します。よろしいですか？" },
                class: "btn btn-danger btn-sm pull-right" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:btn_text, '新規登録') %>

<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1>プロフィール</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-bordered" id="table-user">
      <tr>
        <th class="active col-md-3"><%= User.human_attribute_name :id %></th>
        <td class="col-md-9"><%= @user.id %></td>
      </tr>
      <tr>
        <th class="active"><%= User.human_attribute_name :name %></th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th class="active"><%= User.human_attribute_name :email %></th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th class="active"><%= User.human_attribute_name :created_at %></th>
        <td><%= l(@user.created_at, format: :long) %></td>
      </tr>
    </table>
  </div>    
</div>